#!/bin/sh

# Copyright © 2016-2022 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

prog=${0##*/}
if [ $# -ne 1 ]
then
    printf 'Usage: %s PO-FILE\n' "$prog" >&2
    exit 1
fi
pofile="$1"
exec 3<"$pofile"
lang=$(
    msggrep -K -e '^$' --force-po <&3 \
    | msgexec cat \
    | sed -n -e 's/^Language: *//p'
)
if [ -z "$lang" ]
then
    printf '%s: no language declared\n' "$pofile" >&2
    exit 1
fi
exec msgexec sh -c 'cat; printf "\n"' < "$pofile" \
| mwic --language "$lang"

# vim:ts=4 sts=4 sw=4 et
