boook:
| …wice she had peeped into the boook her
|               is the use of a boook,’ thought Alice ‘without pic…
| …re filled with cubpoards and boook-shelves;
                                ^^^^^

ni:
| …no pictures or conversations ni it, ‘and what
| …s nothing so VERY remarkable ni that; nor did Alice think it…
                                ^^

afterwards, occured:
| …!’ (when she thought it over afterwards, it occured to her
                                ^^^^^^^^^^     ^^^^^^^

labelled:
| …helves as she passed; it was labelled ‘ORANGE MARMALADE’,
                                ^^^^^^^^

cubpoards:
| …d that they were filled with cubpoards and boook-shelves;
                                ^^^^^^^^^

