labelled:
| …helves as she passed; it was labelled ‘ORANGE MARMALADE’,
                                ^^^^^^^^

cubpoards:
| …d that they were filled with cubpoards and boook-shelves;
                                ^^^^^^^^^

aftcrwards, occured:
| …!’ (when she thought it over aftcrwards, it occured to her
                                ^^^^^^^^^^     ^^^^^^^

ni:
| …no pictures or conversations ni it, ‘and what
| …s nothing so VERY remarkable ni that; nor did Alice think it…
                                ^^

boook:
| …wice she had peeped into the boook her
|               is the use of a boook,’ thought Alice ‘without pic…
| …re filled with cubpoards and boook-shelves;
                                ^^^^^

