been know as:
| It has been know as ...
         ^^^^^^^^^^^^

also know as:
| It is also know as ...
        ^^^^^^^^^^^^

being know as:
| It is being know as ...
        ^^^^^^^^^^^^^

better know as:
| It is better know as ...
        ^^^^^^^^^^^^^^

is know as:
| It is know as ...
     ^^^^^^^^^^

was know as:
| It was know as ...
     ^^^^^^^^^^^

be know as:
| It will be know as ...
          ^^^^^^^^^^

are know as:
| They are know as ...
       ^^^^^^^^^^^

were know as:
| They were know as ...
       ^^^^^^^^^^^^

