allow to:
| I allow to go.
    ^^^^^^^^

authorise to:
| I authorise to go.
    ^^^^^^^^^^^^

permit to:
| I permit to go.
    ^^^^^^^^^

allowing to:
| I'm allowing to go.
      ^^^^^^^^^^^

authorising to:
| I'm authorising to go.
      ^^^^^^^^^^^^^^

allows to:
| It allows to go.
     ^^^^^^^^^

authorises to:
| It authorises to go.
     ^^^^^^^^^^^^^

permits to:
| It permits to go.
     ^^^^^^^^^^

authorize:
| I authorize to go.
    ^^^^^^^^^

authorized:
| I'm authorized to go.
      ^^^^^^^^^^

authorizing:
| I'm authorizing to go.
      ^^^^^^^^^^^

authorizes:
| It authorizes to go.
     ^^^^^^^^^^

