He's not ran:
| He's not ran.
  ^^^^^^^^^^^^

He's ran:
| He's ran.
  ^^^^^^^^

ain't ran:
| I ain't ran.
    ^^^^^^^^^

am ran:
| I am ran.
    ^^^^^^

I'm not ran:
| I'm not ran.
  ^^^^^^^^^^^

I'm ran:
| I'm ran.
  ^^^^^^^

been ran:
| It has been ran.
         ^^^^^^^^

being ran:
| It is being ran.
        ^^^^^^^^^

is not ran:
| It is not ran.
     ^^^^^^^^^^

is ran:
| It is ran.
     ^^^^^^

isn't ran:
| It isn't ran.
     ^^^^^^^^^

was not ran:
| It was not ran.
     ^^^^^^^^^^^

was ran:
| It was ran.
     ^^^^^^^

wasn't ran:
| It wasn't ran.
     ^^^^^^^^^^

be ran:
| It will be ran.
          ^^^^^^

It's not ran:
| It's not ran.
  ^^^^^^^^^^^^

It's ran:
| It's ran.
  ^^^^^^^^

She's not ran:
| She's not ran.
  ^^^^^^^^^^^^^

She's ran:
| She's ran.
  ^^^^^^^^^

were not ran:
| They were not ran.
       ^^^^^^^^^^^^

were ran:
| They were ran.
       ^^^^^^^^

weren't ran:
| They weren't ran.
       ^^^^^^^^^^^

They're not ran:
| They're not ran.
  ^^^^^^^^^^^^^^^

They're ran:
| They're ran.
  ^^^^^^^^^^^

We're not ran:
| We're not ran.
  ^^^^^^^^^^^^^

We're ran:
| We're ran.
  ^^^^^^^^^

You're not ran:
| You're not ran.
  ^^^^^^^^^^^^^^

You're ran:
| You're ran.
  ^^^^^^^^^^

