GNU Lesser Public License:
| GNU Lesser Public License
  ^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Library Public License:
| GNU Library Public License
  ^^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Public License:
| GNU Public License
  ^^^^^^^^^^^^^^^^^^

either version 2 of the License:
| either version 2 of the License.
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Licence:
|              GNU Public Licence
|       GNU Lesser Public Licence
|      GNU Library Public Licence
| either version 2 of the Licence, or...
| either version 2 of the Licence.
                          ^^^^^^^

