He's not suppose:
| He's not suppose to return.
  ^^^^^^^^^^^^^^^^

He's suppose:
| He's suppose to return.
  ^^^^^^^^^^^^

ain't suppose:
| I ain't suppose to return.
    ^^^^^^^^^^^^^

am suppose:
| I am suppose to return.
    ^^^^^^^^^^

I'm not suppose:
| I'm not suppose to return.
  ^^^^^^^^^^^^^^^

I'm suppose:
| I'm suppose to return.
  ^^^^^^^^^^^

been suppose:
| It has been suppose to return.
         ^^^^^^^^^^^^

being suppose:
| It is being suppose to return.
        ^^^^^^^^^^^^^

is not suppose:
| It is not suppose to return.
     ^^^^^^^^^^^^^^

is suppose:
| It is suppose to return.
     ^^^^^^^^^^

isn't suppose:
| It isn't suppose to return.
     ^^^^^^^^^^^^^

was not suppose:
| It was not suppose to return.
     ^^^^^^^^^^^^^^^

was suppose:
| It was suppose to return.
     ^^^^^^^^^^^

wasn't suppose:
| It wasn't suppose to return.
     ^^^^^^^^^^^^^^

be suppose:
| It will be suppose to return.
          ^^^^^^^^^^

It's not suppose:
| It's not suppose to return.
  ^^^^^^^^^^^^^^^^

It's suppose:
| It's suppose to return.
  ^^^^^^^^^^^^

She's not suppose:
| She's not suppose to return.
  ^^^^^^^^^^^^^^^^^

She's suppose:
| She's suppose to return.
  ^^^^^^^^^^^^^

were not suppose:
| They were not suppose to return.
       ^^^^^^^^^^^^^^^^

were suppose:
| They were suppose to return.
       ^^^^^^^^^^^^

weren't suppose:
| They weren't suppose to return.
       ^^^^^^^^^^^^^^^

They're not suppose:
| They're not suppose to return.
  ^^^^^^^^^^^^^^^^^^^

They're suppose:
| They're suppose to return.
  ^^^^^^^^^^^^^^^

We're not suppose:
| We're not suppose to return.
  ^^^^^^^^^^^^^^^^^

We're suppose:
| We're suppose to return.
  ^^^^^^^^^^^^^

You're not suppose:
| You're not suppose to return.
  ^^^^^^^^^^^^^^^^^^

You're suppose:
| You're suppose to return.
  ^^^^^^^^^^^^^^

