He's enable:
| He's enable.
  ^^^^^^^^^^^

He's not enable:
| He's not enable.
  ^^^^^^^^^^^^^^^

ain't enable:
| I ain't enable.
    ^^^^^^^^^^^^

am enable:
| I am enable.
    ^^^^^^^^^

I'm enable:
| I'm enable.
  ^^^^^^^^^^

I'm not enable:
| I'm not enable.
  ^^^^^^^^^^^^^^

been enable:
| It has been enable.
         ^^^^^^^^^^^

being enable:
| It is being enable.
        ^^^^^^^^^^^^

is enable:
| It is enable.
     ^^^^^^^^^

is not enable:
| It is not enable.
     ^^^^^^^^^^^^^

isn't enable:
| It isn't enable.
     ^^^^^^^^^^^^

was enable:
| It was enable.
     ^^^^^^^^^^

was not enable:
| It was not enable.
     ^^^^^^^^^^^^^^

wasn't enable:
| It wasn't enable.
     ^^^^^^^^^^^^^

be enable:
| It will be enable.
          ^^^^^^^^^

It's enable:
| It's enable.
  ^^^^^^^^^^^

It's not enable:
| It's not enable.
  ^^^^^^^^^^^^^^^

She's enable:
| She's enable.
  ^^^^^^^^^^^^

She's not enable:
| She's not enable.
  ^^^^^^^^^^^^^^^^

were enable:
| They were enable.
       ^^^^^^^^^^^

were not enable:
| They were not enable.
       ^^^^^^^^^^^^^^^

weren't enable:
| They weren't enable.
       ^^^^^^^^^^^^^^

They're enable:
| They're enable.
  ^^^^^^^^^^^^^^

They're not enable:
| They're not enable.
  ^^^^^^^^^^^^^^^^^^

We're enable:
| We're enable.
  ^^^^^^^^^^^^

We're not enable:
| We're not enable.
  ^^^^^^^^^^^^^^^^

You're enable:
| You're enable.
  ^^^^^^^^^^^^^

You're not enable:
| You're not enable.
  ^^^^^^^^^^^^^^^^^

