an Unicode:
| an Unicode character
  ^^^^^^^^^^

an unary:
| an unary object
  ^^^^^^^^

an unified:
| an unified object
  ^^^^^^^^^^

an uniform:
| an uniform object
  ^^^^^^^^^^

an uniformly:
| an uniformly sized object
  ^^^^^^^^^^^^

an union:
| an union
  ^^^^^^^^

an unique:
| an unique object
  ^^^^^^^^^

an uniquely:
| an uniquely named object
  ^^^^^^^^^^^

an unit:
| an unit
  ^^^^^^^

an universal:
| an universal object
  ^^^^^^^^^^^^

an universally:
| an universally unique identifier
  ^^^^^^^^^^^^^^

an usage:
| an usage
  ^^^^^^^^

an use:
| an use
  ^^^^^^

an useful:
| an useful object
  ^^^^^^^^^

an useless:
| an useless object
  ^^^^^^^^^^

an user:
| an user
  ^^^^^^^

an username:
| an username
  ^^^^^^^^^^^

an utility:
| an utility
  ^^^^^^^^^^

