GNU Lesser Public Licence:
| GNU Lesser Public Licence
  ^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Lesser Public License:
| GNU Lesser Public License
  ^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Library Public Licence:
| GNU Library Public Licence
  ^^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Library Public License:
| GNU Library Public License
  ^^^^^^^^^^^^^^^^^^^^^^^^^^

GNU Public Licence:
| GNU Public Licence
  ^^^^^^^^^^^^^^^^^^

GNU Public License:
| GNU Public License
  ^^^^^^^^^^^^^^^^^^

either version 2 of the Licence:
| either version 2 of the Licence.
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

either version 2 of the License:
| either version 2 of the License.
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

