He's disable:
| He's disable.
  ^^^^^^^^^^^^

He's not disable:
| He's not disable.
  ^^^^^^^^^^^^^^^^

ain't disable:
| I ain't disable.
    ^^^^^^^^^^^^^

am disable:
| I am disable.
    ^^^^^^^^^^

I'm disable:
| I'm disable.
  ^^^^^^^^^^^

I'm not disable:
| I'm not disable.
  ^^^^^^^^^^^^^^^

been disable:
| It has been disable.
         ^^^^^^^^^^^^

being disable:
| It is being disable.
        ^^^^^^^^^^^^^

is disable:
| It is disable.
     ^^^^^^^^^^

is not disable:
| It is not disable.
     ^^^^^^^^^^^^^^

isn't disable:
| It isn't disable.
     ^^^^^^^^^^^^^

was disable:
| It was disable.
     ^^^^^^^^^^^

was not disable:
| It was not disable.
     ^^^^^^^^^^^^^^^

wasn't disable:
| It wasn't disable.
     ^^^^^^^^^^^^^^

be disable:
| It will be disable.
          ^^^^^^^^^^

It's disable:
| It's disable.
  ^^^^^^^^^^^^

It's not disable:
| It's not disable.
  ^^^^^^^^^^^^^^^^

She's disable:
| She's disable.
  ^^^^^^^^^^^^^

She's not disable:
| She's not disable.
  ^^^^^^^^^^^^^^^^^

were disable:
| They were disable.
       ^^^^^^^^^^^^

were not disable:
| They were not disable.
       ^^^^^^^^^^^^^^^^

weren't disable:
| They weren't disable.
       ^^^^^^^^^^^^^^^

They're disable:
| They're disable.
  ^^^^^^^^^^^^^^^

They're not disable:
| They're not disable.
  ^^^^^^^^^^^^^^^^^^^

We're disable:
| We're disable.
  ^^^^^^^^^^^^^

We're not disable:
| We're not disable.
  ^^^^^^^^^^^^^^^^^

You're disable:
| You're disable.
  ^^^^^^^^^^^^^^

You're not disable:
| You're not disable.
  ^^^^^^^^^^^^^^^^^^

