He's consisted of:
| He's consisted of two parts.
  ^^^^^^^^^^^^^^^^^

He's not consisted of:
| He's not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^

ain't consisted of:
| I ain't consisted of two parts.
    ^^^^^^^^^^^^^^^^^^

am consisted of:
| I am consisted of two parts.
    ^^^^^^^^^^^^^^^

I'm consisted of:
| I'm consisted of two parts.
  ^^^^^^^^^^^^^^^^

I'm not consisted of:
| I'm not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^

been consisted of:
| It has been consisted of two parts.
         ^^^^^^^^^^^^^^^^^

being consisted of:
| It is being consisted of two parts.
        ^^^^^^^^^^^^^^^^^^

is consisted of:
| It is consisted of two parts.
     ^^^^^^^^^^^^^^^

is not consisted of:
| It is not consisted of two parts.
     ^^^^^^^^^^^^^^^^^^^

isn't consisted of:
| It isn't consisted of two parts.
     ^^^^^^^^^^^^^^^^^^

was consisted of:
| It was consisted of two parts.
     ^^^^^^^^^^^^^^^^

was not consisted of:
| It was not consisted of two parts.
     ^^^^^^^^^^^^^^^^^^^^

wasn't consisted of:
| It wasn't consisted of two parts.
     ^^^^^^^^^^^^^^^^^^^

be consisted of:
| It will be consisted of two parts.
          ^^^^^^^^^^^^^^^

It's consisted of:
| It's consisted of two parts.
  ^^^^^^^^^^^^^^^^^

It's not consisted of:
| It's not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^

She's consisted of:
| She's consisted of two parts.
  ^^^^^^^^^^^^^^^^^^

She's not consisted of:
| She's not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^^

were consisted of:
| They were consisted of two parts.
       ^^^^^^^^^^^^^^^^^

were not consisted of:
| They were not consisted of two parts.
       ^^^^^^^^^^^^^^^^^^^^^

weren't consisted of:
| They weren't consisted of two parts.
       ^^^^^^^^^^^^^^^^^^^^

They're consisted of:
| They're consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^

They're not consisted of:
| They're not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^^^^

We're consisted of:
| We're consisted of two parts.
  ^^^^^^^^^^^^^^^^^^

We're not consisted of:
| We're not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^^

You're consisted of:
| You're consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^

You're not consisted of:
| You're not consisted of two parts.
  ^^^^^^^^^^^^^^^^^^^^^^^

